import { createContext, useState } from 'react';

export const LanguageContext = createContext();

const translations = {
  es: {
    nav_inicio: "Inicio",
    nav_sobre: "Sobre mí",
    nav_proyectos: "Proyectos",
    nav_cert: "Certificados",
    nav_comentarios: "Comentarios",
    nav_contacto: "Contáctame",
    hero_tagline: "Analista BackOffice  ·  Especialista Cloud  ·  QC en Golbant",
    hero_badge_edu: "Ing. Sistemas — próxima graduación",
    hero_btn_proyectos: "Ver mis proyectos",
    hero_btn_contacto: "Ir a contacto",
    sobre_titulo: "Sobre Mí",
    sobre_subtitulo: "Tecnología + Administración + Resultados",
    sobre_text1: "Soy tecnóloga en formación, a pocos pasos de graduarme como Ingeniera Informatica de UdeCataluña, con un Técnico Laboral en Sistemas cursado en CESDE que fortaleció mis bases prácticas. Actualmente aplico ese conocimiento en el mundo real como QC en Golbant, donde verifico procesos y aseguro estándares de calidad en entornos tecnológicos.",
    sobre_text2: "Me especializo en arquitecturas de nube (AWS, Azure, GCP) y combino ese enfoque técnico con una sólida experiencia administrativa. Mi perfil une lo técnico con lo humano — analizo, ejecuto y comunico.",
    formacion_titulo: "Formación & Experiencia",
    formacion_sub: "Mi camino académico y profesional",
    exp1_titulo: "QC — Golbant",
    exp1_desc: "Prácticas profesionales como Quality Control, verificando procesos y asegurando estándares de calidad en entornos tecnológicos.",
    exp1_badge: "✦ En curso · Prácticas",
    edu1_titulo: "Ingeniería de Sistemas — UdeCataluña",
    edu1_desc: "A pocos pasos de graduarme. Especialización en arquitecturas cloud y desarrollo de software.",
    edu1_badge: "✦ Próxima graduación",
    edu2_titulo: "Técnico Laboral Auxiliar en Sistemas — CESDE",
    edu2_desc: "Fortaleciendo competencias técnicas y prácticas en soporte y administración de sistemas.",
    edu2_badge: "✦ En curso",
    soft_titulo: "Habilidades Blandas",
    soft_sub: "Competencias humanas que me definen",
    soft1: "Adaptabilidad",
    soft2: "Análisis Crítico",
    soft3: "Gestión de Equipos",
    soft4: "Solución de Retos",
    soft5: "Atención al Detalle",
    soft6: "Control de Calidad",
    tech_titulo: "Habilidades Técnicas",
    tech_sub: "Herramientas y tecnologías que domino",
    skill1_nombre: "Arquitecturas Nube (AWS, Azure, GCP)",
    skill1_ctx: "Especialización central · UdeCataluña",
    skill2_nombre: "Desarrollo Web (HTML, CSS, Bootstrap)",
    skill2_ctx: "Demostrado en este portafolio",
    skill3_nombre: "Programación (Python & JS)",
    skill3_ctx: "NumPy y Pandas · proyectos académicos",
    skill4_nombre: "Análisis de Datos & BI",
    skill4_ctx: "Pandas para reportes y clasificaciones",
    skill5_nombre: "Control de Calidad (QC)",
    skill5_ctx: "Práctica activa en Golbant",
    proy_titulo: "Mis Proyectos",
    proy_sub: "Proyectos desarrollados durante mi formación académica",
    proy1_tit: "Sistema de Gestión de Parqueadero",
    proy1_desc: "Sistema en Python con NumPy para administrar un parqueadero de 8 plantas con 5 espacios por planta. Controla ocupación en tiempo real.",
    proy2_tit: "Gestor de Grupo — Mundial de Fútbol",
    proy2_desc: "Plataforma en Python con Pandas para gestionar resultados de un grupo del Mundial. Registra encuentros y consulta tabla de clasificación.",
    proy3_tit: "Juego de Bingo por Consola",
    proy3_desc: "Bingo interactivo en consola. El participante llena su tablero con diez números y se extraen balotas aleatorias hasta encontrar un ganador.",
    github_btn: "Ver en GitHub",
    test_titulo: "Lo que dicen de mi trabajo",
    test_sub: "Opiniones de colegas, profesores y compañeros",
    test1_txt: "\"Yudnaris es una profesional excepcional con una gran capacidad de organización y liderazgo. Su enfoque técnico y su resiliencia la convierten en un activo invaluable.\"",
    test1_autor: "Nicol Alba",
    test1_rol: "Compañero de trabajo y estudio",
    test2_txt: "\"Destaco enormemente su pensamiento crítico y su habilidad para resolver problemas. El dominio que Yudnaris tiene sobre las herramientas digitales es sobresaliente.\"",
    test2_autor: "Wilmar del Valle",
    test2_rol: "Compañero de trabajo y estudio",
    test3_txt: "\"Yudnaris demostró durante su formación en CESDE una capacidad analítica sobresaliente y un compromiso inquebrantable con la calidad del código. Es un profesional que no solo resuelve problemas, sino que busca siempre la eficiencia y la innovación en cada proyecto que emprende.\"",
    test3_autor: "Jorge Pérez",
    test3_rol: "Docente de Desarrollo de Software - CESDE",
    test4_txt: "\"Trabajar con Yudnaris es una experiencia enriquecedora. Su compromiso con la calidad y su disciplina para aprender algo nuevo cada día la hacen destacar en cualquier equipo.\"",
    test4_autor: "Hector Camacho",
    test4_rol: "Mentor",
    test5_txt: "\"Yudnaris tiene una capacidad increíble para entender procesos y proponer mejoras. Su paso por QC en Golbant ha sido notorio — siempre encuentra el detalle que otros pasan por alto.\"",
    test5_autor: "Andrea Tibocha",
    test5_rol: "Compañera de trabajo y estudio",
    test6_txt: "\"Lo que más admiro de Yudnaris es su perseverancia. Combina su formación técnica con una actitud positiva y colaborativa que eleva a todo el equipo a su alrededor.\"",
    test6_autor: "Karol Ahumada",
    test6_rol: "Compañera de trabajo y estudio",
    contacto_titulo: "Contáctame",
    contacto_sub: "¡Trabajemos juntos!",
    contacto_text: "¿Tienes un proyecto en mente, buscas sumar talento a tu equipo o simplemente quieres saludar? Me encantaría conversar contigo.",
    btn_cv: "Descargar CV",
    qr_titulo: "Comparte mi portafolio",
    qr_descripcion: "Escanea este código QR para acceder a mi portafolio desde cualquier dispositivo.",
    qr_descargar: "Descargar QR",
    qr_compartir: "Compartir",
    qr_nota: "El QR contiene el enlace a este portafolio",
    cert_titulo: "Certificados",
    cert_sub: "Reconocimientos y formación continua",
    cert1: "Cátedraser Emprendedor",
    cert2: "Computación Básica",
    cert3: "Inglés A1 Principiantes",
    cert4: "Presente Simple & Vocabulario Común",
    cert5: "Verbo To Be",
    cert6: "Verbos Comunes"
  },
  en: {
    nav_inicio: "Home",
    nav_sobre: "About",
    nav_proyectos: "Projects",
    nav_comentarios: "Testimonials",
    nav_cert: "Certificates",
    nav_contacto: "Contact",
    hero_tagline: "BackOffice Analyst  ·  Cloud Specialist  ·  QC at Golbant",
    hero_badge_edu: "Systems Engineering — graduating soon",
    hero_btn_proyectos: "View my projects",
    hero_btn_contacto: "Go to contact",
    sobre_titulo: "About Me",
    sobre_subtitulo: "Technology + Administration + Results",
    sobre_text1: "I am a technologist in training, about to graduate as a Systems Engineer from UdeCataluña, with a Technical Degree in Systems from CESDE that strengthened my practical foundations. Currently I apply this knowledge in the real world as QC at Golbant, where I verify processes and ensure quality standards in technological environments.",
    sobre_text2: "I specialize in cloud architectures (AWS, Azure, GCP) and combine this technical focus with solid administrative experience. My profile merges technical with human — I analyze, execute, and communicate.",
    formacion_titulo: "Education & Experience",
    formacion_sub: "My academic and professional path",
    exp1_titulo: "QC — Golbant",
    exp1_desc: "Professional internship as Quality Control, verifying processes and ensuring quality standards in technological environments.",
    exp1_badge: "✦ Ongoing · Internship",
    edu1_titulo: "Systems Engineering — UdeCataluña",
    edu1_desc: "About to graduate. Specialization in cloud architectures and software development.",
    edu1_badge: "✦ Graduating soon",
    edu2_titulo: "Technical Assistant in Systems — CESDE",
    edu2_desc: "Strengthening technical skills in support and systems administration.",
    edu2_badge: "✦ In progress",
    soft_titulo: "Soft Skills",
    soft_sub: "Human competencies that define me",
    soft1: "Adaptability",
    soft2: "Critical Analysis",
    soft3: "Team Management",
    soft4: "Problem Solving",
    soft5: "Attention to Detail",
    soft6: "Quality Control",
    tech_titulo: "Technical Skills",
    tech_sub: "Tools and technologies I master",
    skill1_nombre: "Cloud Architectures (AWS, Azure, GCP)",
    skill1_ctx: "Core specialization · UdeCataluña",
    skill2_nombre: "Web Development (HTML, CSS, Bootstrap)",
    skill2_ctx: "Demonstrated in this portfolio",
    skill3_nombre: "Programming (Python & JS)",
    skill3_ctx: "NumPy and Pandas · academic projects",
    skill4_nombre: "Data Analysis & BI",
    skill4_ctx: "Pandas for reports and rankings",
    skill5_nombre: "Quality Control (QC)",
    skill5_ctx: "Active practice at Golbant",
    proy_titulo: "My Projects",
    proy_sub: "Projects developed during my academic training",
    proy1_tit: "Parking Management System",
    proy1_desc: "Python system with NumPy to manage an 8-floor parking lot with 5 spaces per floor. Real-time occupancy control.",
    proy2_tit: "Group Manager — Soccer World Cup",
    proy2_desc: "Python platform with Pandas to manage results of a World Cup group. Registers matches and queries standings.",
    proy3_tit: "Console Bingo Game",
    proy3_desc: "Interactive console Bingo. The participant fills a board with ten numbers and random balls are drawn until a winner is found.",
    github_btn: "View on GitHub",
    test_titulo: "What they say about my work",
    test_sub: "Opinions from colleagues, teachers and peers",
    test1_txt: "\"Yudnaris is an exceptional professional with great organizational and leadership skills. Her technical approach and resilience make her an invaluable asset.\"",
    test1_autor: "Nicol Alba",
    test1_rol: "Work and study colleague",
    test2_txt: "\"I highly highlight her critical thinking and problem-solving skills. Yudnaris's command of digital tools is outstanding.\"",
    test2_autor: "Wilmar del Valle",
    test2_rol: "Work and study colleague",
    test3_txt: "\"Yudnaris demonstrated during her training at CESDE an outstanding analytical ability and an unwavering commitment to code quality. She is a professional who not only solves problems but always seeks efficiency and innovation in every project.\"",
    test3_autor: "Jorge Pérez",
    test3_rol: "Software Development Instructor - CESDE",
    test4_txt: "\"Working with Yudnaris is an enriching experience. Her commitment to quality and her discipline to learn something new every day make her stand out in any team.\"",
    test4_autor: "Hector Camacho",
    test4_rol: "Mentor",
    test5_txt: "\"Yudnaris has an incredible ability to understand processes and propose improvements. Her time as QC at Golbant has been remarkable — she always finds the detail others overlook.\"",
    test5_autor: "Andrea Tibocha",
    test5_rol: "Work and study colleague",
    test6_txt: "\"What I admire most about Yudnaris is her perseverance. She combines her technical training with a positive and collaborative attitude that elevates the whole team around her.\"",
    test6_autor: "Karol Ahumada",
    test6_rol: "Work and study colleague",
    contacto_titulo: "Contact Me",
    contacto_sub: "Let's work together!",
    contacto_text: "Do you have a project in mind, want to add talent to your team or just want to say hello? I'd love to talk with you.",
    btn_cv: "Download CV",
    qr_titulo: "Share my portfolio",
    qr_descripcion: "Scan this QR code to access my portfolio from any device.",
    qr_descargar: "Download QR",
    qr_compartir: "Share",
    qr_nota: "The QR contains the link to this portfolio",
    cert_titulo: "Certificates",
    cert_sub: "Recognitions and continuous learning",
    cert1: "Chair of Entrepreneurship",
    cert2: "Basic Computing",
    cert3: "English A1 Beginners",
    cert4: "Present Simple & Common Vocabulary",
    cert5: "Verb To Be",
    cert6: "Common Verbs"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('es');

  const t = (key) => {
    return translations[language][key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => (prev === 'es' ? 'en' : 'es'));
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
